♻️ Optimize syntax and beautify the code
migros/fotoobo pull request #186
Opened 2024-01-11 08:34 UTC by patrikspiess

- Update docstrings
    - No more types in Args: and Returns: because they are already in function/method definition
    - Aligning texts
- Update Logs
    - Surround %s with ' so they are printed in different color
    - Start all log and error messages with Uppercae
- Remove unused blank lines
- Add blank lines after indented blocks
- Change typing Union[xyz, None] to Optional[xyz]
- Other simple changes

2024-01-23 10:05 UTC, lucmurer requested changes
Very good an thorough cleanup of the code!!

For better legibility I propose to also change the following:
 - Every Python keyword that results in a following block (`if`, `for`, `with`, ...) should be prepended with a blank line, except
     - If the line before is a line comment describing the condition or block
     - If the preceding line is solely for defining a variable that gets used/filled in the block

I would apply the same rules for `return` statements.

I pointed out quite a lot of spots that had a direct change, I saw there are more places in the code which would need cleanup based on my proposal.

If you agree with this proposal please update the pull request again, otherwise I will look again at the pull request and approve it.

2024-01-23 10:05 UTC, lucmurer commented on fotoobo/tools/fmg/get.py
> -
dito

2024-01-23 10:05 UTC, lucmurer commented on fotoobo/tools/fmg/get.py
> -
dito

2024-01-23 10:05 UTC, lucmurer commented on fotoobo/tools/get.py
> -
dito

2024-01-26 10:31 UTC, patrikspiess commented
> Very good an thorough cleanup of the code!!
> 
> For better legibility I propose to also change the following:
> 
> * Every Python keyword that results in a following block (`if`, `for`, `with`, ...) should be prepended with a blank line, except
>   
>   * If the line before is a line comment describing the condition or block
>   * If the preceding line is solely for defining a variable that gets used/filled in the block
> 
> I would apply the same rules for `return` statements.
> 
> I pointed out quite a lot of spots that had a direct change, I saw there are more places in the code which would need cleanup based on my proposal.
> 
> If you agree with this proposal please update the pull request again, otherwise I will look again at the pull request and approve it.

Thank you. I went over all the files and added/removed blank lines as by your suggestion.

2024-01-26 11:47 UTC, lucmurer requested changes
Good job, looks very nice now! 
Just a few typos remaining :-)

2024-01-26 11:47 UTC, lucmurer commented on fotoobo/fortinet/fortigate_config_check.py
> +            msg: The message to sent to the messages list
Typo here: "to sen**d** to"

2024-01-26 11:47 UTC, lucmurer commented on fotoobo/fortinet/fortimanager.py
> +            username: The Username
typo: **u**sername

2024-01-26 11:47 UTC, lucmurer commented on fotoobo/tools/fmg/main.py
> +        file: The configuration file to oad the configuration from
I think "oad" is also a typo here. Should this be "add"?

2024-01-26 12:26 UTC, merged